// <auto-generated />
using System;
using BessIntelligence.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BessIntelligence.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BessIntelligence.Api.Models.AiRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Avg30dSpreadMultiplier")
                        .HasColumnType("float");

                    b.Property<double>("ChargePrice")
                        .HasColumnType("float");

                    b.Property<string>("ChargeWindowEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChargeWindowStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfidencePct")
                        .HasColumnType("float");

                    b.Property<double>("DischargePrice")
                        .HasColumnType("float");

                    b.Property<string>("DischargeWindowEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DischargeWindowStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EstimatedCaptureEur")
                        .HasColumnType("float");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PortfolioAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceSpreadMultiplier")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AiRecommendations");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.Battery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapacityKwh")
                        .HasColumnType("int");

                    b.Property<string>("Chemistry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CommissionedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DurationH")
                        .HasColumnType("float");

                    b.Property<double>("GridConnectionKw")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerRatingKw")
                        .HasColumnType("int");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WiththegridNodeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Batteries");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.BatteryAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteryId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("WindowEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WindowStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("BatteryActions");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.BatteryHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BatteryId")
                        .HasColumnType("int");

                    b.Property<double>("PowerKw")
                        .HasColumnType("float");

                    b.Property<double>("SocPct")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId", "Timestamp");

                    b.ToTable("BatteryHistories");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.BatteryTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryId")
                        .HasColumnType("int");

                    b.Property<double>("CurrentA")
                        .HasColumnType("float");

                    b.Property<string>("FaultCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextActionWindow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PowerKw")
                        .HasColumnType("float");

                    b.Property<double>("SocPct")
                        .HasColumnType("float");

                    b.Property<double>("SohPct")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("VoltageV")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId");

                    b.ToTable("BatteryTelemetries");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.EngineConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Avg30dSpreadMultiplier")
                        .HasColumnType("float");

                    b.Property<double>("CloudMaePct")
                        .HasColumnType("float");

                    b.Property<double>("PriceMaePct")
                        .HasColumnType("float");

                    b.Property<double>("SigmaSohPct")
                        .HasColumnType("float");

                    b.Property<double>("WindRmseMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("EngineConfigs");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.EngineRunStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("EngineRunStatuses");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.MarketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("HourStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceEurMwh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("HourStart");

                    b.ToTable("MarketPrices");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.SolarForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConfidenceHighKw")
                        .HasColumnType("float");

                    b.Property<double>("ConfidenceLowKw")
                        .HasColumnType("float");

                    b.Property<double>("ForecastProductionKw")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("HourStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SolarInstallationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolarInstallationId", "HourStart");

                    b.ToTable("SolarForecasts");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.SolarInstallation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AzimuthDeg")
                        .HasColumnType("float");

                    b.Property<double>("CapacityKwp")
                        .HasColumnType("float");

                    b.Property<DateTime>("CommissionedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("PanelCount")
                        .HasColumnType("int");

                    b.Property<string>("PanelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TiltDeg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("SolarInstallations");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.SolarProduction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CapacityFactorPct")
                        .HasColumnType("float");

                    b.Property<double>("IrradianceWm2")
                        .HasColumnType("float");

                    b.Property<double>("PanelTempC")
                        .HasColumnType("float");

                    b.Property<double>("ProductionKw")
                        .HasColumnType("float");

                    b.Property<int>("SolarInstallationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SolarInstallationId", "Timestamp");

                    b.ToTable("SolarProductions");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmbientTempC")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverPct")
                        .HasColumnType("float");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("HourStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("HumidityPct")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SolarIrradianceWm2")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeedMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "HourStart");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.BatteryAction", b =>
                {
                    b.HasOne("BessIntelligence.Api.Models.Battery", "Battery")
                        .WithMany()
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BessIntelligence.Api.Models.AiRecommendation", "Recommendation")
                        .WithMany("BatteryActions")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.BatteryHistory", b =>
                {
                    b.HasOne("BessIntelligence.Api.Models.Battery", "Battery")
                        .WithMany()
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.BatteryTelemetry", b =>
                {
                    b.HasOne("BessIntelligence.Api.Models.Battery", "Battery")
                        .WithMany()
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Battery");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.SolarForecast", b =>
                {
                    b.HasOne("BessIntelligence.Api.Models.SolarInstallation", "SolarInstallation")
                        .WithMany()
                        .HasForeignKey("SolarInstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarInstallation");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.SolarProduction", b =>
                {
                    b.HasOne("BessIntelligence.Api.Models.SolarInstallation", "SolarInstallation")
                        .WithMany()
                        .HasForeignKey("SolarInstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolarInstallation");
                });

            modelBuilder.Entity("BessIntelligence.Api.Models.AiRecommendation", b =>
                {
                    b.Navigation("BatteryActions");
                });
#pragma warning restore 612, 618
        }
    }
}
